import { StrictMode, useEffect, useRef, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './styles.css';

const images = {
  hero: 'https://images.unsplash.com/photo-1483985988355-763728e1935b?auto=format&fit=crop&w=2000&q=85',
  essentials: 'https://images.unsplash.com/photo-1496747611176-843222e1e57c?auto=format&fit=crop&w=900&q=85',
  tailoring: 'https://images.unsplash.com/photo-1509631179647-0177331693ae?auto=format&fit=crop&w=900&q=85',
  outerwear: 'https://images.unsplash.com/photo-1539109136881-3be0616acf4b?auto=format&fit=crop&w=900&q=85',
  story: 'https://images.unsplash.com/photo-1485230895905-ec40ba36b9bc?auto=format&fit=crop&w=1200&q=85',
  dress: 'https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?auto=format&fit=crop&w=700&q=85',
  knit: 'https://images.unsplash.com/photo-1551488831-00ddcb6c6bd3?auto=format&fit=crop&w=700&q=85',
  jacket: 'https://images.unsplash.com/photo-1551028719-00167b16eac5?auto=format&fit=crop&w=700&q=85',
  trousers: 'https://images.unsplash.com/photo-1591369822096-ffd140ec948f?auto=format&fit=crop&w=700&q=85',
  detail: 'https://images.unsplash.com/photo-1525507119028-ed4c629a60a3?auto=format&fit=crop&w=1000&q=85',
};

const copy = {
  en: { shipping: 'Complimentary shipping on orders over €150', stockholm: 'Designed in Stockholm', shop: 'Shop', newIn: 'New in', story: 'Our story', journal: 'Journal', explore: 'Explore collection', mood: 'Shop by', moodAccent: 'mood', allPieces: 'View all pieces ↗', essentials: 'The essentials', tailoring: 'Soft tailoring', outerwear: 'Outerwear', arrivals: 'New', arrivalsAccent: 'in', allArrivals: 'Shop new arrivals ↗', readStory: 'Read our story', note: 'A note from Hanna', newsletter: 'New collections, quiet inspiration and 10% off your first order.', stay: 'Stay in the know', letters: 'Letters from', less: 'Less, but', better: 'better.', submit: 'Sign me up ↗', email: 'Your email address', footerText: 'Modern essentials, thoughtfully made in Stockholm.', lookbook: 'The lookbook', lookbookAccent: 'in motion', lookbookText: 'A closer look at the textures, shapes and small gestures behind the collection.', values: 'What we', valuesAccent: 'stand for', valueText: 'The details matter. From the first sketch to the final stitch, we make choices with a lighter footprint and a longer life in mind.', valueOne: '01 / Materials', valueOneText: 'Natural fibres and recycled fabrics, chosen for their feel and future.', valueTwo: '02 / Made slowly', valueTwoText: 'Small batches, trusted makers and no unnecessary seasons.', valueThree: '03 / Made to stay', valueThreeText: 'Quiet shapes that become part of your everyday, not a passing trend.' },
  sv: { shipping: 'Fri frakt på beställningar över 1 500 kr', stockholm: 'Designat i Stockholm', shop: 'Shoppa', newIn: 'Nyheter', story: 'Vår berättelse', journal: 'Journal', explore: 'Utforska kollektionen', mood: 'Shoppa efter', moodAccent: 'känsla', allPieces: 'Se alla plagg ↗', essentials: 'Basplaggen', tailoring: 'Mjuk skräddning', outerwear: 'Ytterplagg', arrivals: 'Nytt', arrivalsAccent: '', allArrivals: 'Shoppa nyheter ↗', readStory: 'Läs vår berättelse', note: 'En hälsning från Hanna', newsletter: 'Nya kollektioner, inspiration och 10% på din första beställning.', stay: 'Håll dig uppdaterad', letters: 'Brev från', less: 'Mindre, men', better: 'bättre.', submit: 'Anmäl mig ↗', email: 'Din e-postadress', footerText: 'Moderna basplagg, omsorgsfullt skapade i Stockholm.', lookbook: 'Lookbooken', lookbookAccent: 'i rörelse', lookbookText: 'En närmare titt på texturerna, formerna och detaljerna bakom kollektionen.', values: 'Det här', valuesAccent: 'står vi för', valueText: 'Detaljerna spelar roll. Från den första skissen till sista sömmen gör vi val med mindre avtryck och längre liv i åtanke.', valueOne: '01 / Material', valueOneText: 'Naturliga fibrer och återvunna tyger, valda för känsla och framtid.', valueTwo: '02 / Långsamt skapat', valueTwoText: 'Små upplagor, pålitliga producenter och inga onödiga säsonger.', valueThree: '03 / Skapat för att stanna', valueThreeText: 'Tidlösa former som blir en del av vardagen, inte en tillfällig trend.' }
};

function Arrow() { return <b className="arrow">↗</b>; }
function Eyebrow({ children, centered = false }) { return <div className={`eyebrow mono ${centered ? 'centered' : ''}`}><span>{children}</span></div>; }
function Button({ children, dark = false }) { return <a className={`button ${dark ? 'dark' : ''}`} href="#new">{children} <Arrow /></a>; }

function Header({ t, lang, setLang }) {
  const [open, setOpen] = useState(false);
  return <>
    <div className="announcement mono"><span>{t.shipping}</span><b>✦</b><span>{t.stockholm}</span></div>
    <header><a href="#top" className="logo">Hanna</a><nav className={open ? 'open' : ''}>{[['#shop', t.shop], ['#new', t.newIn], ['#story', t.story], ['#journal', t.journal]].map(([href, label]) => <a href={href} key={href} onClick={() => setOpen(false)}>{label}</a>)}</nav><div className="header-actions"><div className="language"><button className={lang === 'en' ? 'active' : ''} onClick={() => setLang('en')}>EN</button><span>/</span><button className={lang === 'sv' ? 'active' : ''} onClick={() => setLang('sv')}>SV</button></div><button className="icon" aria-label="Search"><svg viewBox="0 0 24 24"><circle cx="10.8" cy="10.8" r="6.7"/><path d="m16 16 5 5"/></svg></button><button className="icon" aria-label="Shopping bag"><svg viewBox="0 0 24 24"><path d="M5 8h14l-1 13H6L5 8Z"/><path d="M9 9V6a3 3 0 0 1 6 0v3"/></svg><span className="bag-count">0</span></button><button className="menu-toggle icon" aria-label="Open menu" onClick={() => setOpen(!open)}><svg viewBox="0 0 24 24"><path d="M3 7h18M3 12h18M3 17h18"/></svg></button></div></header>
  </>;
}

function Reveal({ children, className = '' }) { const ref = useRef(null); useEffect(() => { const observer = new IntersectionObserver(([entry]) => { if (entry.isIntersecting) { entry.target.classList.add('visible'); observer.disconnect(); } }, { threshold: .12 }); if (ref.current) observer.observe(ref.current); return () => observer.disconnect(); }, []); return <div ref={ref} className={`reveal ${className}`}>{children}</div>; }
function Category({ image, title }) { return <a className="category" href="#new"><img src={image} alt=""/><div className="category-copy"><h3>{title}</h3><span className="circle-arrow">↗</span></div></a>; }
function Product({ image, name, detail, price, fresh }) { return <article className="product"><div className="product-image"><img src={image} alt={name}/>{fresh && <span className="tag mono">New</span>}<button className="heart" aria-label="Add to wishlist">♡</button></div><div className="product-info"><div><b>{name}</b><small>{detail}</small></div><span className="product-price">{price}</span></div></article>; }

function App() {
  const [lang, setLang] = useState('en'); const [submitted, setSubmitted] = useState(false); const t = copy[lang];
  return <><Header t={t} lang={lang} setLang={setLang}/><main id="top">
    <section className="hero"><div className="hero-bg"/><div className="hero-content"><Eyebrow>The autumn edit / 2024</Eyebrow><h1>Made for<br/><i>{lang === 'en' ? 'everyday' : 'vardagen'}</i></h1><p>{lang === 'en' ? 'Quiet confidence. Considered silhouettes and pieces that stay with you, season after season.' : 'Tyst självsäkerhet. Genomtänkta silhuetter och plagg som följer med, säsong efter säsong.'}</p><Button>{t.explore}</Button></div><div className="hero-side mono">Hanna — Stockholm / 2024</div><div className="scroll mono">Scroll to discover</div></section>
    <Reveal><section id="shop"><div className="section-head"><h2>{t.mood} <i>{t.moodAccent}</i></h2><a className="text-link" href="#new">{t.allPieces}</a></div><div className="categories"><Category image={images.essentials} title={t.essentials}/><Category image={images.tailoring} title={t.tailoring}/><Category image={images.outerwear} title={t.outerwear}/></div></section></Reveal>
    <Reveal><section id="new" className="products"><div className="section-head"><h2>{t.arrivals} <i>{t.arrivalsAccent}</i></h2><a className="text-link" href="#new">{t.allArrivals}</a></div><div className="product-grid"><Product image={images.dress} name="Alma dress" detail="Black / Organic cotton" price="€129" fresh/><Product image={images.knit} name="Lou knit" detail="Oat / Merino wool" price="€159" fresh/><Product image={images.jacket} name="Isla jacket" detail="Espresso / Recycled leather" price="€299"/><Product image={images.trousers} name="Elin trouser" detail="Stone / Tencel blend" price="€119"/></div></section></Reveal>
    <Reveal><section className="editorial" id="story"><div className="editorial-image"><img src={images.story} alt="Hanna clothing detail"/></div><div className="editorial-copy"><Eyebrow>The Hanna journal / 01</Eyebrow><h2>{t.less} <i>{t.better}</i></h2><p>{lang === 'en' ? 'We believe in a slower wardrobe. One built around thoughtful materials, timeless shapes and the little details that make a piece feel like yours.' : 'Vi tror på en långsammare garderob. En byggd kring genomtänkta material, tidlösa former och detaljerna som gör plagget till ditt.'}</p><Button>{t.readStory}</Button></div></section></Reveal>
    <Reveal><section className="lookbook" id="journal"><div className="lookbook-head"><div><Eyebrow>02 / The visual diary</Eyebrow><h2>{t.lookbook} <i>{t.lookbookAccent}</i></h2></div><p>{t.lookbookText}</p></div><div className="lookbook-grid"><img className="look-one" src={images.detail} alt="Hanna fabric detail"/><img className="look-two" src={images.outerwear} alt="Hanna outerwear look"/><img className="look-three" src={images.knit} alt="Hanna knitwear look"/></div></section></Reveal>
    <Reveal><section className="values"><div className="values-copy"><Eyebrow>03 / Our commitments</Eyebrow><h2>{t.values} <i>{t.valuesAccent}</i></h2><p>{t.valueText}</p></div><div className="value-list"><div><span className="mono">{t.valueOne}</span><p>{t.valueOneText}</p></div><div><span className="mono">{t.valueTwo}</span><p>{t.valueTwoText}</p></div><div><span className="mono">{t.valueThree}</span><p>{t.valueThreeText}</p></div></div></section></Reveal>
    <section className="manifesto"><Eyebrow centered>{t.note}</Eyebrow><h2>“Clothes should make space for <i>{lang === 'en' ? 'life' : 'livet'}</i> to happen.”</h2><p>{lang === 'en' ? 'We make modern essentials in small, intentional collections — for the way you live now, and wherever you’re going next.' : 'Vi skapar moderna basplagg i små, genomtänkta kollektioner — för livet du lever nu och dit du är på väg.'}</p></section>
    <Reveal><section className="newsletter"><Eyebrow centered>{t.stay}</Eyebrow><h2>{t.letters} <i>Hanna</i></h2><p>{t.newsletter}</p><form className="email-form" onSubmit={(e) => { e.preventDefault(); setSubmitted(true); }}><input type="email" placeholder={t.email} aria-label={t.email} required/><button type="submit">{submitted ? (lang === 'en' ? 'Thank you! ↗' : 'Tack! ↗') : t.submit}</button></form></section></Reveal>
  </main><Footer t={t}/></>;
}
function Footer({ t }) { return <footer><div className="footer-top"><div className="footer-brand"><div className="logo">Hanna</div><p className="footer-intro">{t.footerText}</p></div><div><h4>Explore</h4><ul><li><a href="#new">New in</a></li><li><a href="#shop">Collections</a></li><li><a href="#story">Our story</a></li><li><a href="#journal">Journal</a></li></ul></div><div><h4>Help</h4><ul><li><a href="#">Shipping & returns</a></li><li><a href="#">Size guide</a></li><li><a href="#">Contact</a></li><li><a href="#">FAQ</a></li></ul></div><div><h4>Follow</h4><ul><li><a href="#">Instagram ↗</a></li><li><a href="#">Pinterest ↗</a></li><li><a href="#">TikTok ↗</a></li></ul></div></div><div className="footer-bottom"><span>© 2024 Hanna Studio</span><span>Made with intention — Stockholm, Sweden</span><span>Privacy & terms</span></div></footer>; }

createRoot(document.getElementById('root')).render(<StrictMode><App /></StrictMode>);
